# -*- coding: us-ascii-unix -*-

all: check test

check:
	python3 -m pyflakes geocoders guides poor routers
	find . -type f -name "*.json" -print0 | xargs -0 -n 1 tools/check-json

test:
	py.test geocoders guides poor routers
	py.test poor/test/delayed_test_config.py
