#!/usr/bin/env python3
import glob, os
for svg in glob.glob("*.svg"):
    if svg.replace("_", "-") != svg:
        os.rename(svg, svg.replace("_", "-"))
for svg in glob.glob("*.svg"):
    text = open(svg, "r").read()
    text = text.replace('"#000000"', '"#ffffff"')
    open(svg, "w").write(text)
for svg in glob.glob("*.svg"):
    width, height = 64, 64
    for ratio in [1.00, 1.25, 1.50, 1.75, 2.00]:
        png = "{}-medium@{:.2f}.png".format(svg[:-4], ratio)
        os.system("rsvg-convert -w {:.0f} -h {:.0f} -f png -o {} {}"
                  .format(ratio*width, ratio*height, png, svg))
for svg in glob.glob("*.svg"):
    width, height = 96, 96
    for ratio in [1.00, 1.25, 1.50, 1.75, 2.00]:
        png = "{}-large@{:.2f}.png".format(svg[:-4], ratio)
        os.system("rsvg-convert -w {:.0f} -h {:.0f} -f png -o {} {}"
                  .format(ratio*width, ratio*height, png, svg))
