#!/bin/bash

# This script tries to send command to running Pure Maps
# and starts new instance if it fails

set -e

# compose dbus-send command
options=""
for i in $@; do
    if [ ! -z "$options" ]; then
        options="$options,"
    fi
    # have to escape commas due to https://gitlab.freedesktop.org/dbus/dbus/issues/76
    options=$options'"'${i//,/.COMMA.}'"'
done

# INSERT_PLATFORM_STYLE
# INSERT_PLATFORM_FALLBACK_STYLE
dbus-send --session \
          --dest=io.github.rinigus.PureMaps \
          --type=method_call \
          --print-reply \
          /io/github/rinigus/PureMaps \
          io.github.rinigus.PureMaps.command \
          array:string:$options > /dev/null 2>&1 || \
    exec qmlrunner -P INSTALL_PREFIX/share FULL_NAME -- "$@"
