#!/bin/bash

# This script tries to send command to running Pure Maps
# and starts new instance if it fails

set -e

# compose dbus-send command
options=""
for i in "$@"; do
    if [ ! -z "$options" ]; then
        options="$options,"
    fi
    # have to escape commas due to https://gitlab.freedesktop.org/dbus/dbus/issues/76
    options=$options${i//,/.COMMA.}
done

XDG_DATA_DIRS="${XDG_DATA_DIRS:-$HOME/.local/share}":INSTALL_PREFIX/share/FULL_NAME

# INSERT_PLATFORM_STYLE
# INSERT_PLATFORM_FALLBACK_STYLE

# check if called from dbus activation
if [[ $# -eq 1 && "$1" == "--start-directly" ]]; then
    exec QMLRUNNER
    exit 0 # never reached as previous call is exec, keeping for clarity
fi

# proceed to start and/or contact via dbus
dbus-send --session \
          --dest=io.github.rinigus.PureMaps \
          --type=method_call \
          --print-reply \
          /io/github/rinigus/PureMaps \
          io.github.rinigus.PureMaps.Command \
          array:string:"$options" > /dev/null 2>&1 || \
    exec QMLRUNNER -- "$@"
