#!/bin/sh

set -e

if [ "$#" -ne 3 ]; then
    echo "Called without correct arguments"
    echo
    echo "Use: $0 fullname_of_application lconvert install_prefix"
    echo
    exit 1
fi

cd "$(dirname "$0")/.." || exit 1

FULLNAME=$1
LCONVERT=$2
DATADIR=$3

for pname in po/*.po; do
    lang=`basename $pname .po`
    echo Installing translations for $lang
    # GNU gettext translations for Python use.
    mkdir -p ${DATADIR}/locale/${lang}/LC_MESSAGES
    msgfmt ${pname} -o ${DATADIR}/locale/${lang}/LC_MESSAGES/pure-maps.mo
    # Qt linguist translations for QML use.
    mkdir -p ${DATADIR}/translations
    ${LCONVERT} -o ${DATADIR}/translations/${FULLNAME}-${lang}.qm ${pname}
done
