#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os, sys, glob
from apikeys import Keys

if len(sys.argv) != 3 or sys.argv[1] not in ["inject", "strip"]:
    print('Usage: %s inject|strip dirname\nwhere dirname is a root of a project and either strip or inject should be given\n' % sys.argv[0])
    sys.exit(-1)

inject = (sys.argv[1] == "inject")
root = sys.argv[2]

if inject: print('Injecting keys into %s' % root)
else: print( 'Stripping keys from %s' % root)

for dname in ['qml', 'geocoders', 'guides', 'maps', 'routers']:
    for ext in ["py", "qml", "json"]:
        for fname in glob.glob(os.path.join(root, dname, "*." + ext)):
            with open(fname, 'r') as f:
                s = f.read()
            keys = ""
            for k, v in Keys.items():
                if inject:
                    old = k
                    new = v
                else:
                    old = v
                    new = k
                if s.find(old) >= 0:
                    keys += k + " "
                    s = s.replace(old, new)
            if len(keys) > 0:
                print(fname, ":", keys)
                with open(fname, 'w') as f:
                    f.write(s)
